version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - cockroachdb
  cockroachdb:
    image: cockroachdb/cockroach:v20.2.8
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
